### ISSUE TITLE
Book checklist

### ISSUE THREAD

**Issue by aphelionz** [rs-ipfs/offchain-ipfs-manual#4]
- [x] Architectural Explanation
- [x] Contributing / Development intro
- [x] Fix runnable Rust examples
- [x] Arrange offchain::ipfs callables
- [x] More in building an offchain::ipfs intro section?
- [x] Anything else in the getting started section
- [x] CI: https://rust-lang.github.io/mdBook/continuous-integration.html
